POST http://localhost:8081/api/v1/company-globals
Content-Type: application/json

{
	"name": "Company Default2",
	"social_name": "Company Default Social2",
	"cgc": "12345678000195",
	"enabled": true
}