POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
	"name": "Herculano cunha",
	"email": "john.doe2@example.com",
	"password": "securepassword",
	"company_global_id": "b990812e-75f3-4dfa-8e26-8ef43a00f618"
}