POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
	"name": "Herculano cunha",
	"email": "john.doe22@example.com",
	"password": "securepassword",
	"companyGlobalId": 1963596246084001792,
	"roleIds": [1963783084333637632]
}